### ISSUE TITLE
[Question] How can I do RESTful mapping?

### ISSUE THREAD

**Issue by djensen47** [senecajs/seneca-web#108]
I would like to map RESTful API routes calls to action patterns.

For instance, is there a better way to do this (example is for Hapi-style routes (not express/koa):

```
const Routes = [{
  prefix: '/animals',
  pin: 'role:animals,cmd:*',
  map: {
    read: {
      GET: true,
      alias: '/animals/{id}'
    },
    list: {
      GET: true,
      alias: '/animals'
    },
    create: {
      POST: true,
      alias: '/animals'
    },
    update: {
      POST: true,
      alias: '/animals/{id}'
    },
    delete: {
      'DELETE': true,
      alias: '/animals/{id}'
    }
  }
}];
```

**Comment by djensen47** [comment]
Note that the top level prefix is useless in this example. One issue that I ran into is that I cannot override `part`. Here's what I would actually prefer this block of code to look like:

```
const Routes = [{
  prefix: '/api/v1/animals',
  pin: 'role:animals,cmd:*',
  part: false,
  map: {
    read: {
      GET: true,
      suffix: '/{id}'
    },
    list: {
      GET: true
    },
    create: {
      POST: true
    },
    update: {
      POST: true,
      suffix: '/{id}'
    },
    delete: {
      'DELETE': true,
      suffix: '/{id}'
    }
  }
}];
```

**Comment by tswaters** [comment]
Apologies, the docs are kind of out of date.  I've been meaning to fix this up but haven't put together the time to do it properly.

Take a look at this: https://github.com/senecajs/seneca-web/issues/90#issuecomment-249742347 it might help a bit

We added a few options to override specific parts of the generated route path that should make this possible... passing `name` on each map should allow you to get, e.g.

GET /api/v1/animals -- list
GET /api/v1/animals/:id -- get 
POST /api/v1/animals -- create
POST /api/v1/animals/:id -- update
DELETE /api/v1/animals/:id -- delete

I'm on mobile at the moment, will update this with more details when I'm at a proper computer

**Comment by rjstires** [comment]
@tswaters  Maybe I missed something but in the example you've provided, are curly braces the proper syntax for param values? Params appear to be denoted by a colon (:) to function, as clarified #90.

(Just felt this might be worth clarifying as I stumbled a bit due to this post.)

**Comment by djensen47** [comment]
All the "mapper" code does is blindly take strings and create routes on the web server, each one uses a different format. Hapi uses curly braces, express and koa use colons.

**Comment by tswaters** [comment]
I've merged the PR for doc improvements which describes how to do REST mapping.... closing this.

See:  https://github.com/senecajs/seneca-web/blob/f7cfab2/docs/providing-routes.md#rest-example
