### ISSUE TITLE
[Question] get suffix value merged among the other values in the first seneca action parameter

### ISSUE THREAD

**Issue by Walter1976** [senecajs/seneca-web#114]
Hello,
I have a problem following the book 'Developing Microservices with Node.js' by David Gonzales.
In the book seems that doing something like 
```
this.add("init:api", function(msg, respond){
seneca.act('role:web',{ use: {
prefix: '/api',
pin: 'area:ui,action:*',
map: {
products: {GET:true}
productbyid: {GET:true, suffix:'/:id'}
createorder: {POST:true}this.add("init:api", function(msg, respond){
seneca.act('role:web',{ use: {
prefix: '/api',
pin: 'area:ui,action:*',
map: {
products: {GET:true}
productbyid: {GET:true, suffix:'/:id'}
createorder: {POST:true}
}
}}, respond)
});
}
}}, respond)
});
```
I should get the suffix value for the productbyid route directly merged in the args parameter of the action handler:

```
seneca.add({area: "ui", action: "productbyid"}, function(args,
done) {
senecaProductManager.act({area: "product", action: "fetch",
criteria: "byId", id: args.id}, function(err, result) {
done(err, result);
});
});

```
You see that args.id is reused to call another action but however is inside the args object.

I can get the :suffix value in the action handler but only inside the args.args.param object.

For me it's a problem because if I call the handler from another action passing the id I get it inside the first parameter but if I call it from the Rest interface i get inside args.args.param object.

Is there some value I can set inside the Routes definition to obtain the desired behavior?
I am using Seneca (3.2.2), Seneca-web(2.0.0), Express (3.2.6) and seneca-web-adapter-express (1.0.2)

I asked the same thing here just for reference: [http://stackoverflow.com/questions/40422635/query-url-and-body-parameters-not-merged-correctly-in-seneca-with-seneca-web](http://stackoverflow.com/questions/40422635/query-url-and-body-parameters-not-merged-correctly-in-seneca-with-seneca-web)

Thanks in advance,

Walter Bugliarelli

**Comment by Walter1976** [comment]
I got an answer in stackoverflow that makes me believe that I was not understanding well the seneca-web behavior. Probably this post can be closed.

**Comment by dgonzalez** [comment]
Will do. Please fell free to reopen again if you need more help!
