### ISSUE TITLE
more structured way to handle cross-cutting concerns on responses

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-web#12]
e.g. structuring errors

[Trello Card](https://trello.com/c/idQ7hkPN/63-seneca-web-more-structured-way-to-handle-cross-cutting-concerns-on-responses)

**Comment by NickGlenn** [comment]
I'd recommend a simple and straight forward approach using Javascript's native `Error`.  Maybe even take a few notes from how ["Restify" goes about handling errors](http://mcavage.me/node-restify/#error-handling).

**Comment by mcdonnelldean** [comment]
Outdated
