### ISSUE TITLE
TypeError while trying to send response

### ISSUE THREAD

**Issue by nshahcs** [senecajs/seneca-web#120]
I have written a simple action which connects to mongo db using seneca-mongo store module, execute a list query and get the results. I can see that the query was successful and the correct results were fetched. When I try to send these results back to the client, the respond call errors out with following message and stack trace. 

```
ERROR       act     root$           OUT             cmd:getparams,role:diff 11      {cmd:getparams,role:diff,payload:{id:scalaScan}}    ENTRY    (dqk22) -       seneca: Action cmd:getparams,role:diff callback threw: k.indexOf is not a function.     act_callback    {message:k.indexOf is not a function,pattern:cmd:getparams,role:diff,instance:Seneca/0.7.2/d0twcki9cmxg/1485517      TypeError: k.indexOf is not a function
    at /scratch/DiffAnalyzer/node_modules/seneca/node_modules/seneca-web/web.js:851:13
    at Function.forEach (/scratch/DiffAnalyzer/node_modules/lodash/dist/lodash.js:3298:15)
    at Object.defaultmodify [as modify] (/scratch/DiffAnalyzer/node_modules/seneca/node_modules/seneca-web/web.js:850:7)
    at respond (/scratch/DiffAnalyzer/node_modules/seneca/node_modules/seneca-web/web.js:654:22)
    at Seneca.<anonymous> (/scratch/DiffAnalyzer/node_modules/seneca/node_modules/seneca-web/web.js:401:7)
    at act_done (/scratch/DiffAnalyzer/node_modules/seneca/seneca.js:1554:16)
    at /scratch/DiffAnalyzer/node_modules/gate-executor/gate-executor.js:127:20
    at Seneca.<anonymous> (/scratch/DiffAnalyzer/analyze.js:613:5)
    at act_done (/scratch/DiffAnalyzer/node_modules/seneca/seneca.js:1554:16)
    at /scratch/DiffAnalyzer/node_modules/gate-executor/gate-executor.js:127:20
    at /scratch/DiffAnalyzer/node_modules/seneca-mongo-store/mongo-store.js:329:21
    at /scratch/DiffAnalyzer/node_modules/mongodb/lib/mongodb/cursor.js:271:33
    at /scratch/DiffAnalyzer/node_modules/mongodb/lib/mongodb/cursor.js:778:35
    at Cursor.close (/scratch/DiffAnalyzer/node_modules/mongodb/lib/mongodb/cursor.js:1009:5)
    at Cursor.nextObject (/scratch/DiffAnalyzer/node_modules/mongodb/lib/mongodb/cursor.js:778:17)
    at Cursor.each (/scratch/DiffAnalyzer/node_modules/mongodb/lib/mongodb/cursor.js:264:12)
```

The action that I have written is 

```
seneca.add("role:diff,cmd:getparams", function(msg, respond) {
	seneca.ready(function() {
		var collection = seneca.make$("paramStore");
		var f = msg.payload;

		seneca.log.info("Filter", f);
		collection.list$(f, function(err, ob) {
			if (err) {
				seneca.log.error(err);
				respond(err);
			} else {
				seneca.log.info("Result", ob);
				respond(null, ob);
			}
		});
	});
});
```

The same piece of code was working and now I am getting this error. Not sure what changed. Any help/suggestions are greatly appreciated.

**Comment by tswaters** [comment]
The path to seneca-web here reveals the problem:

`/scratch/DiffAnalyzer/node_modules/seneca/node_modules/seneca-web/web.js:851:13`

Older versions of seneca included `seneca-web` as a dependency - this is an older version of the module that seneca might require internally.  This will happen if you don't use an explicit require and use the string form of use, something like this:

    seneca.use('seneca-web')

Make sure you have seneca-web as an explicit dependency and require it when using, 

```js
const SenecaWeb = require('seneca-web')
...
seneca.use(SenecaWeb, {...})
```

You can still look at that version of the module's code - line 851 is here: https://github.com/senecajs/seneca-web/blob/v0.8.0/web.js#L851.... which points at a problem with the routes?

Not sure which version this actually resolves to though, what do you see when you do  `cat  /scratch/DiffAnalyzer/node_modules/seneca/node_modules/seneca-web/package.json | grep version` ?

**Comment by nshahcs** [comment]
I see this output for version
    "type": "version"
  "version": "0.4.3

Currently I am using this was to export seneca actions via express

var app = require('express')()
	.use(require("body-parser").json({
		limit: '50mb'
	}))
	.use(function(req, res, next) {
		res.header("Access-Control-Allow-Origin", "*");
		res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
		res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
		next();
	})
	.use(seneca.export('web'))
	.listen(3032});
Is there something wrong with it? As I mentioned earlier, it was working fine a few days ago.

Also I checked the web.js file. At line 851 it is trying to remove some keys from the result out object that have '$' character in them and erroring out at that point.

 if( _.isObject( result.out ) ) {
    _.each(result.out,function(v,k){
      if(~k.indexOf('$') && 'http$' !== k) {
        delete result.out[k]
      }
    })

My result out object is 
INFO	Result	[{params:[issuename,target,details],id:scalaScan}]
there are no such keys to be removed. I am not sure what v,k represent or if they are getting properly initialized or not. Any fix for this?

**Comment by tswaters** [comment]
`_.each` will iterate over a collection or array. 

- If it's a collection `key` should be each value (i.e.,  results of `Object.keys(collection)`)

- If it's an array `key` will be undefined and you'll get the error you saw.

You can try wrapping the array return in an object, like `respond(null, {data:ob})` -- that'll probably make it work.... 

But, to be honest, I'm not entirely clear how the older versions of `seneca-web` worked.... I'm more familiar with 1.x+ which is where I started using it....   Maybe try updating to latest?  There's a new way to set things up, and a slew of breaking changes from 0.x to 1/2.x,, so it likely won't be a trivial task.

**Comment by nshahcs** [comment]
Yeah, I guess that was it. I was playing with it and figured it out late last night. Respond does not let you return an array, you need to wrap it into an object. 

I tried updating to the latest and I agree, it's not trivial. The changes broke almost all actions that I had written. Thank you very much for the help. :)
