### ISSUE TITLE
How to handle error in seneca-web 2.0

### ISSUE THREAD

**Issue by kasongoyo** [senecajs/seneca-web#122]
Hey folks,

I can't find an example or anywhere in the documentation that show how to handle error and manipulate them before returning them to the API consumer. There is [this example working for seneca 1.0](https://github.com/senecajs/seneca-web/issues/56) but it does't seem to be valid for current seneca.

**Comment by tswaters** [comment]
That looks like it is from seneca-web 0.x.  `responder` doesn't work any more.  When seneca-web went to 1.0 it turned into a thin wrapper to the underlying web framework with everything configured by routes.

It is possible to handle the error and potentially make changes to it prior to sending to the client, but you need to do it in the express (or other) error handler.  There is a test in `seneca-web-adapter-express` that goes over this: https://github.com/senecajs/seneca-web-adapter-express/blob/master/test/express.test.js#L187

In that test, a piece of middleware is attached to the express application:

```js
      app.use((err, req, res, next) => {
        if (res.headersSend) { return next(err) }
        res.status(400).send({message: err.orig.message.replace('gate-executor: ', '')})
      })
```

If you respond with an error in the seneca action, it will make its way to this function... this is where you can potentially do different things with the errors.

Ehh.... most of the time... see https://github.com/senecajs/seneca-web-adapter-express/issues/8 you may need to set `seneca.fixedargs.fatal$ = false`, or you'll likely get a seneca fatal error.

**Comment by kasongoyo** [comment]
Thanks @tswaters for helping me to pinpoint the error handler technique based on express.
