### ISSUE TITLE
Supertest with seneca-web does not work

### ISSUE THREAD

**Issue by kasongoyo** [senecajs/seneca-web#124]
`

    //dependencies
    const Seneca = require('seneca');
    const path = require('path');
    const Web = require('seneca-web');
    const Express = require('express');
    const bodyParser = require('body-parser');
    const config = require('config');

    let app = Express();

    //parsing body
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({
        extended: true
    }));

    // Define all necessary routes to REST API
    const routes = [
        {
            pin: 'route:user,action:*',
            map: {
                'create': {
                    POST: true,
                    alias: '/api/users'
                },
                'get': {
                    GET: true,
                    alias: '/api/users'
                },
                'update': {
                    PUT: true,
                    alias: '/api/users/:id'
                }
            }
        }
    ];

    const senecaWebConfig = {
        adapter: require('seneca-web-adapter-express'),
        options: { parseBody: false },
        context: app
    }

    const seneca = Seneca();
    //Enable to pass error as first argument without fatal error
    seneca.fixedargs.fatal$ = false;

    seneca
        .use('seneca-mongoose', config.get('mongoose'))
        .use('user-plugin')
        .use('./api/user_api')
        .use('mesh', {
            isbase: true,
            pin: "role:api"
        })
        .use(Web, senecaWebConfig);

    seneca.act('role:web', { routes: routes }, (err, reply) => {
        //https://github.com/senecajs/seneca-web/issues/56
        //https://github.com/senecajs/seneca-web-adapter-express/blob/master/test/express.test.js
        app.use((err, req, res, next) => {
            if (res.headersSend) { return next(err) }
            res.status(500).send({ message: err.message });
        });
    });

    module.exports = app;

`

Attached is my application.js that hold the app code. I have exported express instance so that I can be able to plug in the instance to supertest the way I use to run test when I don't using seneca-web, but no routes seems to be found when I run actually test? What difference does the seneca web add that prevent express instance app to have routes.

**Comment by kasongoyo** [comment]
I have figured it out. The test got executed before seneca initialization process complete so I had to increase test timeout and problem has disappeared.

**Comment by dgonzalez** [comment]
You might be interested in the ready callback:
http://senecajs.org/api/#method-ready Not sure if it solves your problem
but it is the way to execute actions when seneca is ready.

Thanks

**Comment by kasongoyo** [comment]
Thanks @dgonzalez.
