### ISSUE TITLE
Pass middleware per route 

### ISSUE THREAD

**Issue by kasongoyo** [senecajs/seneca-web#127]
I appreciate the great work that has been done by the team behind seneca well i have little suggestion if possible to put a way for implementers to be to pass middleware per route. Forexample I prefer my own auth middleware over passport but I don't see a way I can pass my middleware per route

**Comment by tswaters** [comment]
One thing to note is that if routes pass over a microservice boundary, any functions will be stripped (functions can't be transported via json).  That said, you could proxy `role:web,route:*`, use prior actions to add in middleware before it hits `seneca-web`, so I think the case is valid.

I'd like to see how this would be implemented in the various adapters though.  For the connect-style frameworks it's easy enough to prepend middleware, but I don't have a lot of experience with HAPI and I'm not sure off hand how this would look...  Thoughts?

**Comment by kasongoyo** [comment]
Can you elaborate how that can be achieved by proxying `role:web,rote:*`? I agree that we can't pass object within route for the reason you have explained but may be we can pass key value object called may be `middlewareMap` with key as middleware name and value as middleware instance during init of this plugin and only provide keys within the route to direct that the specific route need particular middleware and all those information will be passed down to adapters and adapters can decide which middleware to add to which route. I can add that functionality in `seneca web express adapter` and it will start with `express` atleast.

**Comment by kasongoyo** [comment]
I like the first approach, I think to anticipate maintenance problems, lets pass collection of middleware instead of specific middleware. Something like this:

``` 
seneca = Seneca()
seneca.use(SenecaWeb, {...etc ...})
seneca.ready(() => {
    seneca
        .add('role:web,routes:*', function (msg, cb) {

            msg.middleware = [
                {'middleware1': (req, res, next) => {...etc...}},
                {'middleware2': (req, res, next) => {...etc...}},
            ]
            this.prior(msg, cb)
        })
})
```

Incoming Message

```
{
  "routes": [
    {
      pin: 'role:api,cmd:*',
      map: {
        ping: {
          GET: 'true',
          middleware: ['middleware1', 'middleware2']
        }
      }
    }
  ]
}
```
Then in the `mapRoute`  function of seneca-web we modify like this;
```
function mapRoutes (msg, done) {
  var seneca = this
  var adapter = msg.adapter || locals.adapter
  var context = msg.context || locals.context
  var options = msg.options || locals.options
  var routes = Mapper(msg.routes)
  var auth = msg.auth || locals.auth
  var middleware = msg.middleware || locals.middleware

  // Call the adaptor with the mapped routes, context to apply them to and
  // instance of seneca and the provided consumer callback.
  adapter.call(seneca, options, context, auth, routes, middleware, done)
}
```

Then adapter implementators will inspect route to find if there is middleware key then extract middleware from middleware array and apply it in the context

**Comment by tswaters** [comment]
Terribly sorry for not responding earlier.  My main concern with this is it changes the API contract between `seneca-web` and the adapters.  This will require a major bump and a bunch of staging to make sure we publish new major versions of all the adapters at the same time.  

Also, I liked the other way a bit more - providing functions.... but, at the same time, I can see value in providing named keys as well.  How about both?  We could check if the entry is a string - if so, pull in the middleware -- if it's a function, assume that it is middleware and use that. Of course that concern is more in the adapters and how they deal with this new information.

In terms of `seneca-web` itself 

- provide capability to send object `middleware` key via options object, expected to be an object which each value being a middleware function

- update the mapper to pull in a `middleware` key from both `routeSet` and `route.map` and attach that to the `route`.

Also, we're going to need docs that describe this pretty well I think, another page under ./docs/ called `using middleware` that describes both methods - providing functions in a prior or proxied call.  Or, providing keyed middleware as part of initialization options and using those keys from microservices.

I'll respond also in the PR with specific things that need to happen.
