### ISSUE TITLE
There is a vulnerability seneca-web@2.2.0，please see below

### ISSUE THREAD

**Issue by Cecil0o0** [senecajs/seneca-web#137]
# 环境

node v10.0.0
npm v6.0.0

# 操作步骤

npm audit

# 报错

<div style="text-align:center">=== npm audit security report ===</div>

<div style="text-align:center">
Manual Review<br/>
Some vulnerabilities require your attention to resolve<br/>
Visit https://go.npm.me/audit-guide for additional guidance<br/>
</div>

low     Prototype Pollution
Package      lodash
Dependency of     seneca-web
Path       seneca-web > eraro > lodash
More info    https://nodesecurity.io/advisories/577

[!] 1 vulnerability found - Packages audited: 195 (0 dev, 0 optional)
Severity: 1 low

Please resolve this problem, thanks!!

**Comment by tswaters** [comment]
Working on it, thanks.

**Comment by tswaters** [comment]
Fixed in v2.2.1
