### ISSUE TITLE
Seneca-web Root Prefix

### ISSUE THREAD

**Issue by qnimate** [senecajs/seneca-web#24]
How can I map a action to root path using seneca-web.

For example, this is the prefix:
```
this.act('role:web',{use:{
      prefix: '/'
    }})
```

[Trello Card](https://trello.com/c/mXfaGmOB/67-seneca-web-seneca-web-root-prefix)

**Comment by antjkennedy** [comment]
Hi there,

I appreciate this was asked a few months ago, but happen to have found the solution so may as well leave this hear for others.

To map your commands to the root path you just need to define an empty prefix.

```
seneca.act('role:web', {
  use : {
    prefix : '',
  }});
```

**Comment by mcdonnelldean** [comment]
@mihaidma @mirceaalexandru We should probably add a note on this to the README. @antjkennedy Good spot
