### ISSUE TITLE
Add support for PATCH HTTP method 

### ISSUE THREAD

**Issue by o100ja** [senecajs/seneca-web#25]
Is there any reason why we're not using https://github.com/jshttp/methods in http-router.js line 27?

[Trello Card](https://trello.com/c/57hKrBeM/68-seneca-web-add-support-for-patch-http-method)

**Comment by mcdonnelldean** [comment]
I think it's more of a case that we haven't seen it yet. @rjrodger any thoughts on this one? @geek ?
