### ISSUE TITLE
Is there a way to consume apis provided by another microservice by using map?

### ISSUE THREAD

**Issue by puncha** [senecajs/seneca-web#30]
```JavaScript
seneca.client({host: 'localhost', port: 8081, pin:'role:math'})
seneca.act('role:web',{use:{
  prefix: '/math',
  pin: {role:'math',cmd:'*'},
  map:{
    sum: true
  }
}})
```

**Comment by mcdonnelldean** [comment]
@puncha Sorry for the delay. Do you mean can you call another seneca microservice? If so my understanding is as long as you pin the transport correctly it would work as expected. If not I would most likely suggest this as a feature.

**Comment by m3l7** [comment]
having the same problem. The pin is set up correctly but the command is not called. I have to wrap the action using seneca.add and seneca.act

**Comment by mcdonnelldean** [comment]
@mirceaalexandru May be best to handle this q

**Comment by mirceaalexandru** [comment]
I think not, because when act({role: 'web'}) is called there is checked if the corresponding pattern is defined in seneca. Now, because that pattern is not defined in seneca, that entry from map is ignored. 

This might be a feature request, as @mcdonnelldean said.

**Comment by linde12** [comment]
Does anyone have any news on this? Id love this feature! Right now we have to proxy all api-requests to the correct services

**Comment by mcdonnelldean** [comment]
I'll be removing this check in the next version.

**Comment by linde12** [comment]
Ah, nice! Any clue where this check is? Id like to try it out asap :-)

**Comment by mcdonnelldean** [comment]
So the very raw working version is here:

https://github.com/senecajs/seneca-web/pull/79

There is only one catch. Right now the hapi adaptor will attach request$ and response$ to the message so you can access the properties. I have yet to add in the old properties that were merged. Dollar properties are always stripped on transport so you will basically get a blank message. 

I should have some sample data on that PR in an hour or so. That way you can see data coming through. I see no reason why it won't pin, better yet I'll add an example.

**Comment by linde12** [comment]
Ill have to try it out tomorrow. Good effort!👍

**Comment by mcdonnelldean** [comment]
I've updated the branch, see, 

https://github.com/senecajs/seneca-web/blob/9721ccc00b1d42cd04d354cb50e8cf92272826c0/docs/examples/client-proxy.js

This should show you where the limitation lays when using .client. Having said that, the plan is to add `msg.args` with as many of the stringifable parts from the request as possible so it should still be massively useful. 

Basically we don't have the ability to transport the request / response objects wholesale but we will sent as much of the request as possible for `.client` scenario's.

Express should be done tomorrow.

**Comment by linde12** [comment]
It looks good. I like the API. I'm currently trying to hack something together to get things running and to better understand the code and i think i'm getting the hang of it. Looks like map-routes.js needs some tweaking. For me `_.valueKeys` isn't defined. I'm guessing it should be something like `_.mapKeys`?

**Comment by mcdonnelldean** [comment]
Its like value key but it flattens too.

It's part of lodash so should be there. The implementation is a tad naive in places (eg autostarting servers) but it should be clear enough to change.

Having said that its weird your getting a bug. Can you post your routes? I bet I've missed something there.

Kindest Regards,

Dean

On 2 Sep 2016, at 18:57, Oscar Linde <notifications@github.com<mailto:notifications@github.com>> wrote:


It looks good. I like the API. I'm currently trying to hack something together to get things running and to better understand the code and i think i'm getting the hang of it. Looks like map-routes.js needs some tweaking. For me _.valueKeys isn't defined. I'm guessing it should be something like _.mapKeys?

-

**Comment by linde12** [comment]
I'm getting them same error using the hapi & express examples as well. I don't think lodash has a _valueKeys function, at least i couldn't find it in their docs.

Eventually after some tweaking in map-routes i managed to get my actions triggered, but when responding to the action seneca crashed.

Here is the log output:
```
{
	"notice": "seneca: Action role:web,spec:* failed: _.valueKeys is not a function.",
	"code": "act_execute",
	"err": {
		"eraro": true,
		"orig": {},
		"code": "act_execute",
		"seneca": true,
		"package": "seneca",
		"msg": "seneca: Action role:web,spec:* failed: _.valueKeys is not a function.",
		"details": {
			"message": "_.valueKeys is not a function",
			"pattern": "role:web,spec:*",
			"instance": "Seneca/kostu5ageht9/1472896913338/12346/3.0.0/-",
			"orig$": {},
			"message$": "_.valueKeys is not a function",
			"plugin": {}
		},
		"callpoint": "at /home/linde/js/seneca-web/lib/map-routes.js:14:7"
	},
	"actid": "jkw6jq39m614/9w988wosr2gm",
	"msg": {
		"spec": [{
			"prefix": "/todo",
			"pin": "role:todo,cmd:*",
			"map": {
				"list": true,
				"edit": {
					"autoreply": false,
					"GET": true,
					"POST": true
				}
			}
		}, {
			"prefix": "/admin",
			"pin": "role:admin,cmd:*",
			"map": {
				"validate": {
					"alias": "/login",
					"GET": true
				},
				"signoff": true
			}
		}],
		"role": "web",
		"meta$": {
			"id": "jkw6jq39m614/9w988wosr2gm",
			"tx": "9w988wosr2gm",
			"start": 1472896913430,
			"pattern": "role:web,spec:*",
			"action": "(8l5fwoddtl4n)",
			"entry": true,
			"chain": [],
			"sync": false,
			"plugin_name": "web",
			"plugin_tag": "-"
		},
		"plugin$": {
			"name": "web",
			"tag": "-"
		},
		"tx$": "9w988wosr2gm"
	},
	"entry": true,
	"prior": [],
	"meta": {
		"plugin_name": "web",
		"plugin_tag": "-",
		"plugin_fullname": "web",
		"raw": {
			"role": "web",
			"spec": "*"
		},
		"sub": false,
		"client": false,
		"args": {
			"role": "web",
			"spec": "*"
		},
		"rules": {},
		"id": "(8l5fwoddtl4n)",
		"pattern": "role:web,spec:*",
		"msgcanon": {
			"role": "web",
			"spec": "*"
		},
		"priorpath": ""
	},
	"client": false,
	"listen": false,
	"transport": {},
	"kind": "act",
	"case": "ERR",
	"duration": 2,
	"level": "error",
	"seneca": "kostu5ageht9/1472896913338/12346/3.0.0/-",
	"when": 1472896913442
}
```

**Comment by mcdonnelldean** [comment]
Oh! I think I know what this is. I was finalising the name and was refactoring names. I bet I've mangled mapKeys into valuekeys by replacing map with value.

I've a couple of hours set aside today so I can fix. I ran the examples and changed at the last minute. Typical :)?

Kindest Regards,

Dean

On 3 Sep 2016, at 11:07, Oscar Linde <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm getting them same error using the hapi & express examples as well. I don't think lodash has a _valueKeys function, at least i couldn't find it in their docs.

Eventually after some tweaking in map-routes i managed to get my actions triggered, but when responding to the action seneca crashed.

Here is the log output:

{
    "notice": "seneca: Action role:web,spec:* failed: _.valueKeys is not a function.",
    "code": "act_execute",
    "err": {
        "eraro": true,
        "orig": {},
        "code": "act_execute",
        "seneca": true,
        "package": "seneca",
        "msg": "seneca: Action role:web,spec:* failed: _.valueKeys is not a function.",
        "details": {
            "message": "_.valueKeys is not a function",
            "pattern": "role:web,spec:*",
            "instance": "Seneca/kostu5ageht9/1472896913338/12346/3.0.0/-",
            "orig$": {},
            "message$": "_.valueKeys is not a function",
            "plugin": {}
        },
        "callpoint": "at /home/linde/js/seneca-web/lib/map-routes.js:14:7"
    },
    "actid": "jkw6jq39m614/9w988wosr2gm",
    "msg": {
        "spec": [{
            "prefix": "/todo",
            "pin": "role:todo,cmd:*",
            "map": {
                "list": true,
                "edit": {
                    "autoreply": false,
                    "GET": true,
                    "POST": true
                }
            }
        }, {
            "prefix": "/admin",
            "pin": "role:admin,cmd:*",
            "map": {
                "validate": {
                    "alias": "/login",
                    "GET": true
                },
                "signoff": true
            }
        }],
        "role": "web",
        "meta$": {
            "id": "jkw6jq39m614/9w988wosr2gm",
            "tx": "9w988wosr2gm",
            "start": 1472896913430,
            "pattern": "role:web,spec:*",
            "action": "(8l5fwoddtl4n)",
            "entry": true,
            "chain": [],
            "sync": false,
            "plugin_name": "web",
            "plugin_tag": "-"
        },
        "plugin$": {
            "name": "web",
            "tag": "-"
        },
        "tx$": "9w988wosr2gm"
    },
    "entry": true,
    "prior": [],
    "meta": {
        "plugin_name": "web",
        "plugin_tag": "-",
        "plugin_fullname": "web",
        "raw": {
            "role": "web",
            "spec": "*"
        },
        "sub": false,
        "client": false,
        "args": {
            "role": "web",
            "spec": "*"
        },
        "rules": {},
        "id": "(8l5fwoddtl4n)",
        "pattern": "role:web,spec:*",
        "msgcanon": {
            "role": "web",
            "spec": "*"
        },
        "priorpath": ""
    },
    "client": false,
    "listen": false,
    "transport": {},
    "kind": "act",
    "case": "ERR",
    "duration": 2,
    "level": "error",
    "seneca": "kostu5ageht9/1472896913338/12346/3.0.0/-",
    "when": 1472896913442
}


-

**Comment by linde12** [comment]
Haha, sounds like myself!

No hurries, let me know if you need someone to try it out!

**Comment by mcdonnelldean** [comment]
Should be fixed now!

It was indeed silly edits on my parts. Tests are coming Monday so this shouldn't happen again!

Kindest Regards,

Dean

On 3 Sep 2016, at 11:36, Oscar Linde <notifications@github.com<mailto:notifications@github.com>> wrote:


Haha, sounds like myself!

No hurries, let me know if you need someone to try it out!

-

**Comment by linde12** [comment]
I did some testing today and it works fine.

What i'm doing is having microservices register themselves to the webserver:

`service.act({role: 'api', cmd: 'register', pin: 'role:v1', routes: {prefix: '/api/v1', pin: 'role:v1,cmd:*', map: {echo: true}})`

Then the webserver does a `seneca.client({port: msg.port, pin: msg.pin})` and `seneca.act('role:web', {routes: routes})`

This makes it so that i can redeploy single services independently without gateway downtime and i can add new api versions without any downtime at all. Do you think this is a good approach?

Everything works fine so far.

**Comment by mcdonnelldean** [comment]
@linde12 Good call, I'll see can I get that in. For now master is updated and ready for publish.

**Comment by shonabell** [comment]
I think I'm having the same problem.. can someone tell me what I'm doing wrong?
//server.js
'use strict'

let Seneca = require('seneca');
let SenecaWeb = require('seneca-web');
let Express = require('express');
let BodyParser = require('body-parser');


const app = Express()
    .use(BodyParser.urlencoded({extended: true}))


const senecaWebConfig = {
    context: app,
    adapter: require('seneca-web-adapter-express'),
    routes: []
};


let seneca = Seneca()
    .use(SenecaWeb, senecaWebConfig)
    .use("mesh",{
        isbase: true,
        listen: [{
            pin: 'role:user', model: 'observe'
        }]
   })
    .ready(() => {
        let server = seneca.export('web/context')()

        server.listen(5555, (err) => {
            console.log(err || 'server started on: 5555')
        });
        console.log(seneca.list())
    });

//microservice-1.js

const Seneca = require('seneca');

Seneca({tag: 'user'})
    .use('web')
    .use(function user(options) {

        this.add('role:user,cmd:load', function (msg, reply) {
            var user = {
                id: 1,
                first_name: 'u1',
                last_name: 'u1',
            };
            reply(user);
        });

        this.add('role:user,cmd:list', function (msg, reply) {
            var user = [{
                id: 1,
                first_name: 'u1',
                last_name: 'u1',
            }, {
                id: 2,
                first_name: 'u2',
                last_name: 'u2',
            }, {
                id: 3,
                first_name: 'u3',
                last_name: 'u3',
            }];
            reply(user);
        });


        this.add('init:user', (msg, reply) => {
            this.act('role:web', { routes: [{
                    prefix: '/user',
                    pin: 'role:user,cmd:*',
                    map: {
                        load: {
                            GET: true,
                            name: '',
                            suffix: '/:id',
                            // auth: {
                            //     strategy: 'jwt'
                            // }
                        },
                        list: {
                            GET: true,
                            name: '',
                        }

                    }
                }]

            });
        }
    );

        return 'user';
    })
    .use('mesh', {
        pin: 'role:user'
    })
    .listen({port: 9900, pin: 'role:user'})
    .ready(() => {

    })

**Comment by tswaters** [comment]
Oof, please don't necro old posts.  Seems unlikely this is the same problem -- this was a bad version of the library that referenced a non-existent function in lodash.
