### ISSUE TITLE
Propagating Seneca error to Express "next" function.

### ISSUE THREAD

**Issue by peek4y** [senecajs/seneca-web#36]
Is there a way, to propagate a seneca error, to next(err) ?

**Comment by mcdonnelldean** [comment]
@rjrodger @mihaidma Not too sure but this does sound like it's the right way to do this?

**Comment by mirceaalexandru** [comment]
@mcdonnelldean From my understanding if Seneca processed that request and has reported an error then this should not be propagated to "next". Take in consideration the scenario when a service requires authorization. In this case the seneca-auth will report auth error and seneca-web will report that further. But this error should not go to next Express middleware, in my opinion, as that should be reported directly to the client.

**Comment by peek4y** [comment]
Is it possible to provide "propagating to next" as an option?

**Comment by mirceaalexandru** [comment]
@peek4y  

Yes we can do that, it will be in the next version.

**Comment by peek4y** [comment]
@mirceaalexandru Awesome, looking forward for the updates!

**Comment by mirceaalexandru** [comment]
@peek4y please take a look in Readme for role:web,handle:response

**Comment by peek4y** [comment]
Cool! Thanks.
