### ISSUE TITLE
endware

### ISSUE THREAD

**Issue by ro70** [senecajs/seneca-web#57]
Hello

[Here](https://github.com/senecajs/seneca-web/blob/master/web.js#L165) there is an endware object. Is this functionality implemented? If yes, how do I have to use it (tried it like startware but without success)? What are the use cases?

Thanks for your help.

**Comment by geek** [comment]
@ro70 `endware` will be mapped to `postmap` which is documented here: https://github.com/senecajs/seneca-web/blob/89608112e3f9ecb7fe676b9f1da5d1b6ca41c85b/README.md#general-middleware

**Comment by mcdonnelldean** [comment]
Endware is dow deprecated in favour of a more lightweight system. All middleware should be done external to seneca-web.
