### ISSUE TITLE
Trailing slash on prefix is not optional when using blank alias

### ISSUE THREAD

**Issue by sdbondi** [senecajs/seneca-web#63]
With the following code:

```javascript
    seneca.act('role:web', {
      use: {
        prefix: '/batch',
        plugin: `${__dirname}/endpoints/batch`,
        pin: 'role:api, handler:batch, cmd:*',

        map: {
          create: { alias: '', POST: true },
        },
      },
    });

```

I have to make the request with a trailing slash i.e `/batch/` works, `/batch` doesn't.
What happens is [this line in fixprefix](https://github.com/senecajs/seneca-web/blob/master/web.js#L1105) adds a trailing slash, but the `http-router` module 
seems to already add `\/?` (optional trailing slash) to the match regex. So you get `"\/batch\/\/?"
which only matches trailing slashes.

I'm not too familiar with the `seneca-web` code but removing the addition of a trailing slash in `fixprefix`
results in the trailing slash being optional in the request. Perhaps `path.join` should be used to ensure that if an alias is used it is joined properly to the prefix, or remove a trailing slash before passing to `http-router`. 

I can work around this by:
```javascript
    seneca.act('role:web', {
      use: {
        prefix: '/',
        pin: 'role:api, handler:batch, cmd:*',

        map: {
          create: { alias: '/batch', POST: true },
        },
      },
    });
```
But I prefer to use the prefix. This trailing slash issue has cost me some time trying to figure out what is wrong with my `seneca` and route definitions, so fixing this should save people some time.

Happy to make a PR if you think that I'm on the right page here, and are willing to wait a while for it - need to get on with not debugging a trailing slash issue ;)

**Comment by mcdonnelldean** [comment]
Fixed on master via #79
