### ISSUE TITLE
Arguments being overridden (id, name)

### ISSUE THREAD

**Issue by christophla** [senecajs/seneca-web#66]
I am new to seneca and I am having problems with values being overridden somewhere along the way.

- When posting a json document to an endpoint the name property is being changed to 'Seneca/2.1.0/4yw8nu2odgdw/1466611077816/12280/-'

```json
{
  "name" : "My Name"
}
```

- When mapping an 'id' to an action, it gets changed to a long string of numbers.

```javascript
update: {
  PUT: true,
   alias: 'datasets/:id'
},
```

**Comment by christophla** [comment]
I figured out that I need to add data: true to the map

```javascript
update: {
 PUT: true,
 alias: 'datasets/:datasetId',
 data: true
 }
```

The documentation incorrectly states that the property is `dataprop` when the correct one is `data`

The id is still being incorrectly mapped as a string of random numbers...

**Comment by mirceaalexandru** [comment]
@mcdonnelldean the id issue is still there or is fixed? Seems that id is still changed.

**Comment by ro70** [comment]
@mirceaalexandru @mcdonnelldean In issue https://github.com/senecajs/seneca/issues/348 I'm reporting on the same problem. It's not only the id that changes, although name, version, ... are showing this behaviour. It's not fixed yet.

Here's another minimal example (tested with seneca 2.1.0, express 4.14.0, body-parser 1.15.2):
```
var app = require('express')()
var seneca = require('seneca')()

seneca.add('role: user, cmd: readId', function(args, done) {
  console.log('id=', args.id)
  done()
})
seneca.add('role: user, cmd: readName', function(args, done) {
  console.log('name=', args.name)
  done()
})
seneca.add('role: user, cmd: readVersion', function(args, done) {
  console.log('version=', args.name)
  done()
})

seneca.act({role: 'web', use: {
    prefix: '/',
    pin: {role: 'user', cmd: '*'},
    map: {
      readId: {GET: true, alias: '/user/id/:id'},
      readName: {GET: true, alias: '/user/name/:name'},
      readVersion: {GET: true, alias: '/user/version/:version'},
    }
  }
})

app.use(require('body-parser').json())
app.use(seneca.export('web'))
app.listen(3000)

// curl -m 1 -s http://localhost:3000/user/id/99  => args.id = 3g1ic496delu/1468573431086/53372/-
// curl -m 1 -s http://localhost:3000/user/name/maria => args.name = Seneca/2.1.0/3g1ic496delu/1468573431086/53372/-
// curl -m 1 -s http://localhost:3000/user/version/1.0 => args.version = Seneca/2.1.0/123ih5bf1gr5/1468573577694/53554/-

```

**Comment by mirceaalexandru** [comment]
Hey @ro70 , I know that you reported this, didn't know the current status for this.

:+1:
