### ISSUE TITLE
Do not work over amqp transport

### ISSUE THREAD

**Issue by surfdude75** [senecajs/seneca-web#68]
It seems it does not work when using amqp as transport.

When I set transport to amqp using .client method it does not work anymore.

But If I add a local .add and then call the .act targeting amqp endpoint it works

Here is how I make it works in coffeescript:

merge = (dest,src,props) ->
  props.forEach (prop) ->
    dest[prop] = src[prop] if src[prop] and !dest[prop]
  dest

add = (seneca,cmd,target,allowedParameters) ->
  seneca.add
    role: 'api'
    cmd: cmd
  , (args,done) ->
    params = merge target, args, allowedParameters
    @act params, done

module.exports = (seneca) ->
  seneca.client
    type: 'amqp'
    url: process.env.AMQP_URL
    pin: 'role:frame-data'

  add seneca, 'next',
    role: 'frame-data'
    cmd: 'next'
  , [ 'camera', 'position', 'n', 'time' ]

  add seneca, 'previous',
    role: 'frame-data'
    cmd: 'previous'
  , [ 'camera', 'position', 'n', 'time' ]

  add seneca, 'info',
    role: 'frame-data'
    cmd: 'info'
  , [ 'camera', 'position']

  seneca.act 'role:web',
    use:
      prefix: '/api'
      pin: role:'api', cmd:'*'
      map:
        info: true
        next: true
        previous: true

It could be much easier going directly to role: 'frame-data' that is in amqp endpoint

Is it due to security?

**Comment by mirceaalexandru** [comment]
Hey @surfdude75,

Yes, is a known constraint. Is working only if matching a local defined pattern. This is because the validation of the endpoints is done before the transport being available, so only local defined actions are considered.

**Comment by mcdonnelldean** [comment]
Done as of #79  Serializable parts of the request are now in msg.args and is transportable.
