### ISSUE TITLE
Arg Namespacing

### ISSUE THREAD

**Issue by bitmage** [senecajs/seneca-web#73]
Is there a way to prefix user-defined args such that the end up in a sub key?  Such as:

```javascript
{
    role: 'foo',
    cmd: 'bar',
    args: {my: 'args', go: 'here'}
}
```

The reason I ask is that there's a lot of other noise in the root namespace.  Stuff from Seneca core, stuff from plugins.  It makes it hard to troubleshoot and see what params are being sent.  If we could have some separation in the namespacing it would make it all much clearer.

One way to solve this would be by having `seneca.exports('web')` take a prefix:

```javascript
seneca.exports('web', {argPrefix: 'arg'})
```

Thoughts?  Would this break the overall intention around pattern matching?  Are there unintended consequences that I'm missing?

**Comment by mcdonnelldean** [comment]
Done in the latest version
