### ISSUE TITLE
Break out sub-modules

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/seneca-web#94]
For reasons given by @tswaters in #80 it makes complete sense to drop express / hapi / connect support into their respective libraries.

Koa cannot be added to this repo because it requires newer syntax elements then we use. This came up in the previous iteration of seneca-web and caused issues. 

It'd be nice to have express, hapi, connect, koa1 and koa2 support as separate modules to keep the implementation clean as possible. @tswaters has already created Koa and Koa2 support. 

@tswaters I'm really bad for bandwidth for the next 2.5 weeks. If you want to split them out I'd be more than happy to then transfer all 5 from your account into senecajs/ directly. You would be considered maintainer on them all and wouldn't loose any access (It is all still licensed to you).

Let me know your thoughts. If your time limited too we can look at this in late Oct.

**Comment by tswaters** [comment]
I've started work on this.  I transferred the koa1/2 adapters to senecajs org.  

I updated the references in the badges in the readme to point @ senecajs.  

- Travis seems to work OK and it is monitoring PRs

- Coveralls is returning a 404.  I think administrators need to do something there to get it to work.

- didn't publish new npm version, so the readme/repo still points at `tswaters` on their page, I think that is pretty minor.

A few other things relating to the work - 

- the `read-body.js` is shared between connect and express.  I've just copied the file out into the sub-modules.  I'm not sure if this really warrants a separate module at all.

- some of the tests depend on changes that are in master but not in npm.  I've made the devDependency to seneca-web use `"seneca-web": "github:senecajs/seneca-web"` to fix that.

- once I create the repos under senecajs I imagine some minor administrative work will need to take place to turn on travis/coveralls (unless it is automagical, I'm not entirely sure)
