### ISSUE TITLE
Need better docs for route mapping options

### ISSUE THREAD

**Issue by tswaters** [senecajs/seneca-web#96]
I was going to add some docs about suffix, but realized there wasn't really a good place for it aside from the quick example, and that doesn't really describe the nuance of the various parameters.

Currently the following are supported on a given route:

``` js
{
  prefix: '',
  postfix: '',
  map: {
    route: {
      alias: '',
      suffix: ''
    }
  }
```

If alias is used, it overwrites everything.

Otherwise, the returned path will be the following:

``` js
const path = `${prefix}${postfix}${part}${suffix}`
```

where `part` in the above is the key of the map, "route" in the example above

**Comment by mcdonnelldean** [comment]
Yeah alias is basically an override. On docs It might be now harm to add in a single doc called `route-mapping-options.md` and raw dump some examples and explainations into it. 

It doesn't have to be pretty, that can come later. Just do like the above.

**Comment by tswaters** [comment]
Closing this.

See https://github.com/senecajs/seneca-web/blob/f7cfab2/docs/providing-routes.md
